Repository warrr-mansion/backend, pull requests merged in 2025-05, with the labels that each got.

#7 🔀 챗봇 대화 API 구현 및 최근 대화 내역 주입
  pom.xml
  src/main/java/com/warrr/zipflex/ZipflexApplication.java
  src/main/java/com/warrr/zipflex/api/chatbot/controller/ChatBotController.java
  src/main/java/com/warrr/zipflex/api/chatbot/domain/document/ChatMessage.java
  src/main/java/com/warrr/zipflex/api/chatbot/domain/model/RoleType.java
  src/main/java/com/warrr/zipflex/api/chatbot/dto/in/ChatMessageRequestDto.java
  src/main/java/com/warrr/zipflex/api/chatbot/dto/out/ChatMessageResponseDto.java
  src/main/java/com/warrr/zipflex/api/chatbot/service/ChatBotAsyncProcessor.java
  src/main/java/com/warrr/zipflex/api/chatbot/service/ChatBotService.java
  src/main/java/com/warrr/zipflex/api/chatbot/service/ChatBotServiceImpl.java
  src/main/java/com/warrr/zipflex/global/config/OpenAiConfig.java
  src/main/java/com/warrr/zipflex/global/config/RedisConfig.java
  src/main/java/com/warrr/zipflex/global/response/BaseResponseStatus.java
Labels: ✨ enhancement, 👷 chore

#6 🔀 조건별 매물, 실거래가 조회 기능 구현
  pom.xml
  src/main/java/com/warrr/zipflex/api/house/controller/DealInfoController.java
  src/main/java/com/warrr/zipflex/api/house/controller/HouseInfoController.java
  src/main/java/com/warrr/zipflex/api/house/dao/ApartmentDealDao.java
  src/main/java/com/warrr/zipflex/api/house/dao/DealDao.java
  src/main/java/com/warrr/zipflex/api/house/dao/HouseInfoDao.java
  src/main/java/com/warrr/zipflex/api/house/dao/OfficetelDealDao.java
  src/main/java/com/warrr/zipflex/api/house/dao/VillaDealDao.java
  src/main/java/com/warrr/zipflex/api/house/dto/out/DealInfoResponseDto.java
  src/main/java/com/warrr/zipflex/api/house/dto/out/HouseInfoResponseDto.java
  src/main/java/com/warrr/zipflex/api/house/service/DealInfoService.java
  src/main/java/com/warrr/zipflex/api/house/service/DealInfoServiceImpl.java
  src/main/java/com/warrr/zipflex/api/house/service/HouseInfoService.java
  src/main/java/com/warrr/zipflex/api/house/service/HouseInfoServiceImpl.java
  src/main/java/com/warrr/zipflex/global/response/BaseResponseStatus.java
  src/main/java/com/warrr/zipflex/global/support/CursorPage.java
  src/main/java/com/warrr/zipflex/global/support/PageRequestDto.java
  src/main/java/com/warrr/zipflex/global/support/PageResponseDto.java
  src/main/resources/mapper/ApartmentDealMapper.xml
  src/main/resources/mapper/HouseInfoMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/OfficetelDealMapper.xml
  src/main/resources/mapper/VillaDealMapper.xml
Labels: ✨ enhancement

#9 🚑️ 병합 충돌로 인한 컴파일 에러 수정
  src/main/java/com/warrr/zipflex/api/house/service/DealInfoServiceImpl.java
  src/main/java/com/warrr/zipflex/global/response/BaseResponseStatus.java
Labels: 🐛 bug, 🚑️ hotfix

#10 🚀 챗봇, 부동산 매물 및 실거래가 API 구현
  .github/workflows/cicd.yml
  .husky/commit-msg
  Dockerfile
  pom.xml
  src/main/java/com/warrr/zipflex/ZipflexApplication.java
  src/main/java/com/warrr/zipflex/api/chatbot/controller/ChatBotController.java
  src/main/java/com/warrr/zipflex/api/chatbot/domain/document/ChatMessage.java
  src/main/java/com/warrr/zipflex/api/chatbot/domain/model/RoleType.java
  src/main/java/com/warrr/zipflex/api/chatbot/dto/in/ChatMessageRequestDto.java
  src/main/java/com/warrr/zipflex/api/chatbot/dto/out/ChatMessageResponseDto.java
  src/main/java/com/warrr/zipflex/api/chatbot/service/ChatBotAsyncProcessor.java
  src/main/java/com/warrr/zipflex/api/chatbot/service/ChatBotService.java
  src/main/java/com/warrr/zipflex/api/chatbot/service/ChatBotServiceImpl.java
  src/main/java/com/warrr/zipflex/api/house/controller/DealInfoController.java
  src/main/java/com/warrr/zipflex/api/house/controller/HouseInfoController.java
  src/main/java/com/warrr/zipflex/api/house/dao/ApartmentDealDao.java
  src/main/java/com/warrr/zipflex/api/house/dao/DealDao.java
  src/main/java/com/warrr/zipflex/api/house/dao/HouseInfoDao.java
  src/main/java/com/warrr/zipflex/api/house/dao/OfficetelDealDao.java
  src/main/java/com/warrr/zipflex/api/house/dao/VillaDealDao.java
  src/main/java/com/warrr/zipflex/api/house/dto/out/DealInfoResponseDto.java
  src/main/java/com/warrr/zipflex/api/house/dto/out/HouseInfoResponseDto.java
  src/main/java/com/warrr/zipflex/api/house/service/DealInfoService.java
  src/main/java/com/warrr/zipflex/api/house/service/DealInfoServiceImpl.java
  src/main/java/com/warrr/zipflex/api/house/service/HouseInfoService.java
  src/main/java/com/warrr/zipflex/api/house/service/HouseInfoServiceImpl.java
  src/main/java/com/warrr/zipflex/global/aspect/ServiceLoggingAspect.java
  src/main/java/com/warrr/zipflex/global/config/OpenAiConfig.java
  src/main/java/com/warrr/zipflex/global/config/RedisConfig.java
  src/main/java/com/warrr/zipflex/global/config/SwaggerConfig.java
  src/main/java/com/warrr/zipflex/global/response/BaseResponse.java
  src/main/java/com/warrr/zipflex/global/response/BaseResponseStatus.java
  src/main/java/com/warrr/zipflex/global/support/CursorPage.java
  src/main/java/com/warrr/zipflex/global/support/PageRequestDto.java
  src/main/java/com/warrr/zipflex/global/support/PageResponseDto.java
  src/main/java/com/warrr/zipflex/global/support/TypeCaster.java
  src/main/resources/mapper/ApartmentDealMapper.xml
  src/main/resources/mapper/HouseInfoMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/OfficetelDealMapper.xml
  src/main/resources/mapper/VillaDealMapper.xml
Labels: ✨ enhancement, 👷 chore, 🚀 deploy

#12 🚑️ Swagger 버전 충돌 에러 수정
  .husky/commit-msg
  pom.xml
Labels: 🐛 bug, 🚑️ hotfix

#11 🚑️ Swagger 버전 충돌 에러 수정
  .husky/commit-msg
  pom.xml
Labels: 🐛 bug, 🚑️ hotfix

#13 🔀 공지사항 CRUD
  src/main/java/com/warrr/zipflex/api/notice/controller/NoticeController.java
  src/main/java/com/warrr/zipflex/api/notice/dao/NoticeDao.java
  src/main/java/com/warrr/zipflex/api/notice/dto/in/NoticeCreateRequestDto.java
  src/main/java/com/warrr/zipflex/api/notice/dto/in/NoticeUpdateRequestDto.java
  src/main/java/com/warrr/zipflex/api/notice/dto/out/NoticeInfoResponseDto.java
  src/main/java/com/warrr/zipflex/api/notice/service/NoticeService.java
  src/main/resources/mapper/NoticeMapper.xml
Labels: ✨ enhancement

#14 🔀 지역 조회 요청 api 구현
  src/main/java/com/warrr/zipflex/api/region/controller/RegionController.java
  src/main/java/com/warrr/zipflex/api/region/dao/RegionDao.java
  src/main/java/com/warrr/zipflex/api/region/dto/DongDto.java
  src/main/java/com/warrr/zipflex/api/region/dto/GugunDto.java
  src/main/java/com/warrr/zipflex/api/region/dto/SidoDto.java
  src/main/java/com/warrr/zipflex/api/region/service/RegionService.java
  src/main/java/com/warrr/zipflex/api/region/service/RegionServiceImpl.java
  src/main/resources/mapper/RegionMapper.xml
Labels: ✨ enhancement

#15 🔀 Security 설정 및 회원가입/로그인 기능 구현
  .husky/commit-msg
  pom.xml
  src/main/java/com/warrr/zipflex/api/auth/controller/AuthController.java
  src/main/java/com/warrr/zipflex/api/auth/domain/model/AuthUserDetail.java
  src/main/java/com/warrr/zipflex/api/auth/domain/model/Authority.java
  src/main/java/com/warrr/zipflex/api/auth/domain/model/TokenType.java
  src/main/java/com/warrr/zipflex/api/auth/dto/in/ReIssueTokenRequestDto.java
  src/main/java/com/warrr/zipflex/api/auth/dto/in/SignInRequestDto.java
  src/main/java/com/warrr/zipflex/api/auth/dto/in/SignUpRequestDto.java
  src/main/java/com/warrr/zipflex/api/auth/dto/out/JwtTokenResponseDto.java
  src/main/java/com/warrr/zipflex/api/auth/dto/out/SignInResponseDto.java
  src/main/java/com/warrr/zipflex/api/auth/service/AuthService.java
  src/main/java/com/warrr/zipflex/api/auth/service/AuthServiceImpl.java
  src/main/java/com/warrr/zipflex/api/auth/service/AuthUserDetailService.java
  src/main/java/com/warrr/zipflex/api/auth/service/JwtTokenService.java
  src/main/java/com/warrr/zipflex/api/auth/service/JwtTokenServiceImpl.java
  src/main/java/com/warrr/zipflex/api/auth/vo/in/SignInRequestVo.java
  src/main/java/com/warrr/zipflex/api/auth/vo/in/SignUpRequestVo.java
  src/main/java/com/warrr/zipflex/api/auth/vo/out/SignInResponseVo.java
  src/main/java/com/warrr/zipflex/api/chatbot/controller/ChatBotController.java
  src/main/java/com/warrr/zipflex/api/chatbot/service/ChatBotAsyncProcessor.java
  src/main/java/com/warrr/zipflex/api/chatbot/service/ChatBotServiceImpl.java
  src/main/java/com/warrr/zipflex/api/house/controller/DealInfoController.java
  src/main/java/com/warrr/zipflex/api/house/controller/HouseInfoController.java
  src/main/java/com/warrr/zipflex/api/house/dao/HouseInfoDao.java
  src/main/java/com/warrr/zipflex/api/member/dao/MemberDao.java
  src/main/java/com/warrr/zipflex/api/member/domain/entity/Member.java
  src/main/java/com/warrr/zipflex/api/member/domain/model/Role.java
  src/main/java/com/warrr/zipflex/api/member/domain/model/State.java
  src/main/java/com/warrr/zipflex/api/member/dto/out/MemberResponseDto.java
  src/main/java/com/warrr/zipflex/global/config/AuthenticationConfig.java
  src/main/java/com/warrr/zipflex/global/config/SecurityConfig.java
  src/main/java/com/warrr/zipflex/global/exception/handler/AuthenticationEntryPointHandler.java
  src/main/java/com/warrr/zipflex/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/warrr/zipflex/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/warrr/zipflex/global/jwt/JwtTokenProvider.java
  src/main/java/com/warrr/zipflex/global/jwt/properties/CorsProperties.java
  src/main/java/com/warrr/zipflex/global/jwt/properties/JwtProperties.java
  src/main/java/com/warrr/zipflex/global/response/BaseResponseStatus.java
  src/main/java/com/warrr/zipflex/global/support/PageResponseDto.java
  src/main/resources/mapper/MemberMapper.xml
Labels: ✨ enhancement, 👷 chore

#17 🔀 공지사항 CRUD 로직 수정
  src/main/java/com/warrr/zipflex/api/house/dto/out/DealInfoResponseDto.java
  src/main/java/com/warrr/zipflex/api/notice/controller/NoticeController.java
  src/main/java/com/warrr/zipflex/api/notice/dao/NoticeDao.java
  src/main/java/com/warrr/zipflex/api/notice/dto/in/NoticeCreateRequestDto.java
  src/main/java/com/warrr/zipflex/api/notice/dto/in/NoticeUpdateRequestDto.java
  src/main/java/com/warrr/zipflex/api/notice/service/NoticeService.java
  src/main/resources/mapper/ApartmentDealMapper.xml
  src/main/resources/mapper/NoticeMapper.xml
Labels: ♻️ refactor
